### PR TITLE
Fix for small screens

### PR DESCRIPTION
**Pull request by frknkrc44**
I just added Nodes as PopupSubMenuMenuItem and looks better

New

### CODE REVIEW

**Comment by maxgallup** [comment]
Hey, I appreciate the effort, however It was intentional to be able to see all nodes after just clicking on the extension once. Do you have so many tailscale nodes that the list becomes too long for you? If so, then I could maybe add a "view more nodes" button that after clicking it reveals all of them. 

Also, how is this a fix for small screens?

**Comment by frknkrc44** [comment]
Yes, I have too much nodes and the popup menu doesn't fit to my small screen (1366x768) so I inserted all nodes to the PopupSubMenuMenuItem. I prepared this PR because GNOME's popup menus doesn't have any scroller as default and if we add them to the PopupSubMenuMenuItem, nodes section will have a scroller and can fit to every screen (even you have too much nodes).

**Comment by maxgallup** [comment]
Ok, I see. I will think about it and perhaps try to find a solution that works for both cases. Probably if number of nodes > 15? then it will be a PopupSubMenuMenuItem, like you said and otherwise it will just be a MenuItem.

**Comment by frknkrc44** [comment]
I think 15 is too much for small screens, 5 nodes are enough to hide them in PopupSubMenuMenuItem as default (you can add a setting for this too, maybe some users can think to hide all nodes -like my method- or show every node). But it needs too much effort to add/remove nodes in 2 menus at same time. I still think PopupSubMenuMenuItem way is enough for all screens.

**Comment by matdave** [comment]
This is great. I have a large screen, but WAY too many nodes.

**Comment by der-eismann** [comment]
Since I created #21 - we use Tailscale at a company level and we currently have 47 nodes. That causes the list to fill my whole screen and hides the buttons below, so a solution like this would be highly appreciated.

**Pull request merged**
